import streamlit 
import os
import streamlit as st
from fpdf import FPDF
from agent.analyzer import DetectiveAgent

st.set_page_config(
    page_title="Detective Agentic AI",
    page_icon="🔍",
    layout="wide"
)

# ---------------------------------------------------------
# Sidebar Admin Panel (Case JSON Uploader)
# ---------------------------------------------------------
st.sidebar.title("🏢 Agency Admin Panel")
st.sidebar.markdown("Upload new legacy case files directly into your ChromaDB vector database.")

uploaded_file = st.sidebar.file_uploader("Upload Case File (.json)", type=["json"])

if uploaded_file is not None:
    cases_dir = "cases"
    os.makedirs(cases_dir, exist_ok=True)
    file_path = os.path.join(cases_dir, uploaded_file.name)
    
    with open(file_path, "wb") as f:
        f.write(uploaded_file.getbuffer())
        
    st.sidebar.success(f"✅ Indexed '{uploaded_file.name}' into vector database!")
st.sidebar.divider()

# ---------------------------------------------------------
# PDF Generation Function (Cleaned for fpdf2)
# ---------------------------------------------------------
def generate_pdf(result: dict) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "INVESTIGATIVE SUSPECT RISK REPORT", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 8, "Generated by Detective Agentic AI Platform", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)
    
    # Suspect Details & Metrics
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, f"Suspect Name / Alias: {result.get('suspect_name', 'Unknown')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Tendency Score: {result.get('tendency_score', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Risk Assessment Level: {result.get('risk_level', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    
    # Executive Summary
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 6, "Executive Summary & AI Assessment:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, result.get("summary", "No summary available."))
    pdf.ln(6)
    
    # Matched Precedents
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 6, "Top Historical Precedent Matches (ChromaDB RAG):", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    
    similar_cases = result.get("similar_cases", [])
    if similar_cases:
        for idx, case in enumerate(similar_cases, 1):
            meta = case.get("metadata", {})
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, f"Match {idx}: {meta.get('title', 'Historical Case')} (Case ID: {case.get('case_id')})", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(0, 5, f"Location: {meta.get('location', 'Unknown')} | Type: {meta.get('crime_type', 'Unknown')}", new_x="LMARGIN", new_y="NEXT")
            
            snippet = case.get('snippet', '')
            if len(snippet) > 250:
                snippet = snippet[:250] + "..."
            pdf.multi_cell(0, 5, f"Snippet: {snippet}")
            pdf.ln(3)
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 5, "No direct matching precedent cases found.", new_x="LMARGIN", new_y="NEXT")
        
    return bytes(pdf.output())

# ---------------------------------------------------------
# Streamlit Main Dashboard UI
# ---------------------------------------------------------
st.title("🕵️‍♂️ Agentic AI Suspect Profiler & Case Matcher")
st.write("Vector-based RAG analysis connecting suspect behaviors to indexed historical case precedents.")

st.divider()

col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("📋 Suspect Profile Input")
    suspect_name = st.text_input("Suspect Name / Alias", value="Suspect Alpha")
    behavior = st.text_area("Observed Behaviors", placeholder="e.g. Stalking victims, high deceitfulness, meticulous planning...")
    mo = st.text_area("Suspected Modus Operandi (MO)", placeholder="e.g. Laced drinks with toxic substance...")
    personality = st.text_area("Personality Notes", placeholder="e.g. Lack of empathy, narcissism, deceitfulness...")
    
    analyze_btn = st.button("Analyze Criminal Tendencies", use_container_width=True, type="primary")

with col2:
    st.subheader("📊 Intelligence Assessment")
    if analyze_btn:
        with st.spinner("Executing RAG Vector Query & Agent Analysis..."):
            agent = DetectiveAgent()
            result = agent.evaluate_suspect(suspect_name, behavior, mo, personality)
            
            # Metrics
            m1, m2 = st.columns(2)
            m1.metric(label="Tendency Score", value=result.get("tendency_score"))
            m2.metric(label="Risk Assessment Level", value=result.get("risk_level"))
            
            st.info(result.get("summary"))
            
            # Matched Cases
            st.markdown("### 🔍 Top Matched Precedents")
            similar_cases = result.get("similar_cases", [])
            
            if similar_cases:
                for idx, case in enumerate(similar_cases, 1):
                    meta = case.get("metadata", {})
                    with st.expander(f"Case {idx}: {meta.get('title', 'Historical Record')} ({meta.get('crime_type', 'N/A')})"):
                        st.write(f"**Location:** {meta.get('location', 'Unknown')}")
                        st.write(f"**Case ID:** {case.get('case_id')}")
                        st.caption(f"**Indexed Profile Snippet:** {case.get('snippet')}")
            else:
                st.write("No matching historical cases found in database.")
                
            st.divider()
            
            # Download PDF Button
            try:
                pdf_bytes = generate_pdf(result)
                st.download_button(
                    label="📄 Download Executive PDF Report",
                    data=pdf_bytes,
                    file_name=f"{suspect_name.replace(' ', '_')}_Risk_Report.pdf",
                    mime="application/pdf",
                    use_container_width=True
                )
            except Exception as e:
                st.error(f"Could not generate PDF: {e}")  